-- Highlight policy for the semantic terminal palette generated by thememanager.
-- Neovim stays in cterm mode; the terminal maps slots 0-15 to theme-specific
-- hex values. Keep semantic highlights on these slots so theme changes preserve
-- intent. Use rgb()/grey() only for derived xterm backgrounds and neutral ramps.

local M = {}

--- @param r integer 0-5 inclusive
--- @param g integer 0-5 inclusive
--- @param b integer 0-5 inclusive
local function rgb(r, g, b)
  return 16 + r * 36 + g * 6 + b
end

--- @param shade integer 0-23 inclusive
local function grey(shade)
  -- Invert the greyscale on light backgrounds so low shades are near-white
  -- and high shades are near-black, preserving contrast in both modes.
  local idx = vim.o.background == "light" and (23 - shade) or shade
  return 232 + idx
end

-- Read the thememanager palette.json once and cache the raw content.
-- Returns nil when the file isn't present (non-thememanager environment).
local palette_cache = nil
local palette_loaded = false
local function read_palette()
  if palette_loaded then
    return palette_cache
  end
  palette_loaded = true
  local data_home = os.getenv("XDG_DATA_HOME") or (os.getenv("HOME") .. "/.local/share")
  local f = io.open(data_home .. "/theme/palette.json", "r")
  if not f then
    return nil
  end
  palette_cache = f:read("*a")
  f:close()
  return palette_cache
end

local function invalidate_palette()
  palette_cache = nil
  palette_loaded = false
end

--- @param hex string 6-char hex string
--- @return number perceived luminance 0–255
local function luminance(hex)
  local r = tonumber(hex:sub(1, 2), 16) or 0
  local g = tonumber(hex:sub(3, 4), 16) or 0
  local b = tonumber(hex:sub(5, 6), 16) or 0
  return 0.299 * r + 0.587 * g + 0.114 * b
end

-- Set vim.o.background based on the Palette Artifact surface color.
-- No-op when palette.json isn't present.
function M.detect_background()
  local content = read_palette()
  if not content then
    return
  end
  local bg_hex = content:match('"surface"%s*:%s*"#?([0-9a-fA-F]+)"')
  if not bg_hex or #bg_hex < 6 then
    return
  end
  vim.o.background = luminance(bg_hex) > 127 and "light" or "dark"
end

---@class (exact) HighlightOpts
---@field fg? integer
---@field bg? integer
---@field bold? true
---@field italic? true
---@field underline? true
---@field undercurl? true
---@field strikethrough? true
---@field reverse? true
---@field [integer] string Groups to extend from

---@param t table<string, string | HighlightOpts>
local function create_theme(t)
  vim.g.colors_name = "custom"
  vim.o.termguicolors = false

  -- Collect all (group, opts) pairs first, then apply in one batch.
  -- This avoids triggering Neovim's internal highlight invalidation on every
  -- single nvim_set_hl call; the redraw happens once after the flush.
  local pending = {} -- { { name, opts } ... }

  local highlights = {}
  local function add_highlight(k, v)
    if v == nil then
      error("highlight not defined in config: " .. k)
    end
    if type(v) == "string" then
      local opts = highlights[v] or add_highlight(v, t[v])
      highlights[k] = opts
      pending[#pending + 1] = { k, { link = v } }
      return opts
    else
      local opts
      if
        #v ~= 1
        or v.fg
        or v.bg
        or v.bold
        or v.italic
        or v.underline
        or v.undercurl
        or v.strikethrough
        or v.reverse
      then
        opts = {
          ctermfg = v.fg,
          ctermbg = v.bg,
          cterm = {
            bold = v.bold,
            italic = v.italic,
            strikethrough = v.strikethrough,
            underline = v.underline,
            undercurl = v.undercurl,
            reverse = v.reverse,
          },
        }
        for _, name in ipairs(v) do
          local h = highlights[name] or add_highlight(name, t[name])
          opts = {
            ctermfg = opts.ctermfg or h.ctermfg,
            ctermbg = opts.ctermbg or h.ctermbg,
            cterm = {
              bold = opts.cterm.bold or h.cterm.bold,
              italic = opts.cterm.italic or h.cterm.italic,
              strikethrough = opts.cterm.strikethrough or h.cterm.strikethrough,
              underline = opts.cterm.underline or h.cterm.underline,
              undercurl = opts.cterm.undercurl or h.cterm.undercurl,
              reverse = opts.cterm.reverse or h.cterm.reverse,
            },
          }
        end
        pending[#pending + 1] = { k, opts }
      else
        opts = highlights[v[1]] or add_highlight(v[1], t[v[1]])
        pending[#pending + 1] = { k, { link = v[1] } }
      end
      highlights[k] = opts
      return opts
    end
  end

  -- Resolve the full inheritance graph (no API calls yet)
  for k, v in pairs(t) do
    if not highlights[k] then
      add_highlight(k, v)
    end
  end

  -- Flush: apply all highlights in one tight loop
  local hl = vim.api.nvim_set_hl
  for i = 1, #pending do
    hl(0, pending[i][1], pending[i][2])
  end
end

-- Re-read the palette, optionally override &background, and re-apply highlights.
-- Called by scripts/apply-theme via --remote-expr when thememanager swaps the palette.
---@param bg? "light" | "dark"
function M.reload(bg)
  invalidate_palette()
  if bg == "light" or bg == "dark" then
    vim.o.background = bg
  else
    M.detect_background()
  end
  M.apply()
end

function M.apply()
  local BG = 0
  local DANGER = 1
  local SUCCESS = 2
  local WARNING = 3
  local ACCENT = 4
  local ACCENT_ALT = 5
  local INFO = 6
  local TEXT = 7
  local MUTED = 8
  local DANGER_BRIGHT = 9
  local SUCCESS_BRIGHT = 10
  local WARNING_BRIGHT = 11
  local ACCENT_BRIGHT = 12
  local ACCENT_ALT_BRIGHT = 13
  local TEXT_BRIGHT = 15

  create_theme({
    -- ── Primitives ────────────────────────────────────────────────────────
    Constant = { fg = WARNING },
    Literal = { fg = WARNING },
    Number = "Literal",
    Float = "Literal",
    Character = "Literal",
    Boolean = { fg = ACCENT_ALT },
    String = { fg = WARNING },
    SpecialChar = { fg = SUCCESS },

    -- ── Identifiers ───────────────────────────────────────────────────────
    Identifier = {}, -- plain text color
    Variable = "Identifier",
    Function = { fg = ACCENT_ALT },

    -- ── Statements ────────────────────────────────────────────────────────
    Statement = { fg = SUCCESS },
    Conditional = "Statement",
    Repeat = "Statement",
    Label = { fg = ACCENT },
    Operator = { fg = grey(10) }, -- subtle — operators recede
    Keyword = "Statement",
    Exception = { fg = SUCCESS },

    -- ── Preprocessor ──────────────────────────────────────────────────────
    PreProc = { fg = ACCENT_ALT_BRIGHT },
    Include = { fg = SUCCESS },
    Define = { fg = ACCENT_ALT },
    Macro = { fg = ACCENT_ALT_BRIGHT },
    PreCondit = { fg = ACCENT_ALT_BRIGHT },

    -- ── Types ─────────────────────────────────────────────────────────────
    Type = { fg = ACCENT, bold = true },
    StorageClass = { fg = ACCENT },
    Structure = { fg = ACCENT },
    Typedef = { fg = ACCENT_BRIGHT },

    -- ── Diagnostics ───────────────────────────────────────────────────────
    Error = { fg = DANGER },
    Warning = { fg = WARNING },
    Info = { fg = INFO },
    Hint = { fg = ACCENT },
    Success = { fg = SUCCESS },

    ErrorMsg = { fg = DANGER_BRIGHT, bold = true },
    WarningMsg = "Warning",
    InfoMsg = "Info",
    HintMsg = "Hint",
    SuccessMsg = "Success",

    DiagnosticError = { fg = DANGER_BRIGHT },
    DiagnosticWarn = "Warning",
    DiagnosticInfo = "Info",
    DiagnosticHint = "Hint",
    DiagnosticOk = "Success",

    DiagnosticUnderlineError = { "DiagnosticError", undercurl = true },
    DiagnosticUnderlineWarn = { "DiagnosticWarn", undercurl = true },
    DiagnosticUnderlineHint = { "DiagnosticHint", undercurl = true },
    DiagnosticUnderlineInfo = { "DiagnosticInfo", undercurl = true },
    DiagnosticUnderlineOk = { "DiagnosticOk", undercurl = true },

    DiagnosticSignError = "DiagnosticError",
    DiagnosticSignWarn = "DiagnosticWarn",
    DiagnosticSignHint = "DiagnosticHint",
    DiagnosticSignInfo = "DiagnosticInfo",
    DiagnosticSignOk = "DiagnosticOk",

    DiagnosticUnnecessary = { fg = MUTED }, -- muted/faded
    DiagnosticDeprecated = { fg = MUTED, strikethrough = true },

    DiagnosticVirtualTextError = "DiagnosticError",
    DiagnosticVirtualTextWarn = "DiagnosticWarn",
    DiagnosticVirtualTextInfo = "DiagnosticInfo",
    DiagnosticVirtualTextHint = "DiagnosticHint",
    DiagnosticVirtualTextOk = "DiagnosticOk",

    -- ── Health ────────────────────────────────────────────────────────────
    healthError = "Error",
    healthSuccess = "Success",
    healthWarning = "Warning",

    -- ── Redraw debug ──────────────────────────────────────────────────────
    RedrawDebugClear = { fg = BG, bg = WARNING },
    RedrawDebugComposed = { fg = BG, bg = SUCCESS },
    RedrawDebugRecompose = { fg = BG, bg = DANGER },

    -- ── Spelling ──────────────────────────────────────────────────────────
    SpellBad = { "Error", undercurl = true },
    SpellCap = { "Warning", undercurl = true },
    SpellRare = { "Info", undercurl = true },
    SpellLocal = { "Hint", undercurl = true },

    -- ── Special ───────────────────────────────────────────────────────────
    Special = { fg = ACCENT },
    SpecialKey = { fg = MUTED }, -- muted — non-printable chars
    Tag = { fg = ACCENT },
    Delimiter = { fg = MUTED }, -- muted — brackets/parens recede
    SpecialComment = { fg = ACCENT_ALT, italic = true },

    -- ── Prose / markup ────────────────────────────────────────────────────
    Title = { fg = ACCENT, bold = true },
    Todo = { fg = ACCENT_ALT, bold = true },
    Note = { fg = ACCENT, bold = true },
    Question = { fg = WARNING },
    Comment = { fg = grey(10), italic = true }, -- subtle

    -- ── Navigation / UI chrome ────────────────────────────────────────────
    Directory = { fg = ACCENT },

    -- Neutral greys (theme-adaptive via grey())
    GreyBg1 = { bg = grey(1) },
    GreyBg2 = { bg = grey(2) },
    GreyBg3 = { bg = grey(3) },
    GreyBg4 = { bg = grey(8) },

    GreyFg1 = { fg = grey(4) },
    GreyFg2 = { fg = grey(6) },
    GreyFg3 = { fg = grey(12) },

    -- ── Base text ─────────────────────────────────────────────────────────
    Normal = { fg = TEXT }, -- plain buffer text (let terminal handle bg)
    NormalNC = { fg = TEXT }, -- non-current window text

    -- ── Messages ──────────────────────────────────────────────────────────
    ModeMsg = { fg = MUTED }, -- --INSERT-- etc. mode indicator (subtle)
    MoreMsg = { fg = ACCENT_ALT }, -- --More-- prompt
    Debug = { fg = ACCENT_ALT }, -- debug output
    Underlined = { fg = ACCENT_ALT, underline = true },

    -- ── Cursor / selection ────────────────────────────────────────────────
    Cursor = { reverse = true },
    Visual = { bg = grey(4) },
    VisualNOS = "Visual",

    CursorLine = "GreyBg4",
    CursorLineNr = { "CursorLine", fg = TEXT, bold = true },
    CursorLineSign = "CursorLine",
    CursorLineFold = "CursorLine",
    CursorColumn = "CursorLine",
    ColorColumn = { bg = grey(3) },

    -- ── Search ────────────────────────────────────────────────────────────
    Search = { fg = MUTED, bg = WARNING_BRIGHT },
    CurSearch = { fg = MUTED, bg = ACCENT_ALT, bold = true },
    IncSearch = "CurSearch",

    -- ── Completion / wildmenu ─────────────────────────────────────────────
    WildMenu = { fg = BG, bg = ACCENT, bold = true },
    MatchParen = { fg = WARNING, bg = grey(5), bold = true },
    QuickFixLine = { fg = ACCENT, bold = true },

    Pmenu = { fg = grey(12) },
    PmenuSbar = "GreyBg2",
    PmenuThumb = "GreyBg4",
    PmenuSel = { fg = TEXT_BRIGHT, bg = grey(5), bold = true },
    PmenuKind = { fg = ACCENT },
    PmenuKindSel = { "PmenuSel", fg = ACCENT_BRIGHT },
    PmenuExtra = { fg = TEXT },
    PmenuExtraSel = { "PmenuSel", fg = MUTED },

    -- ── Tabs / statusline ─────────────────────────────────────────────────
    TabLine = "GreyBg2",
    TabLineSel = { bg = grey(4), fg = TEXT, bold = true },
    TabLineFill = "GreyBg1",

    StatusLine = { bg = grey(3), fg = TEXT },
    StatusLineNC = { bg = grey(1), fg = MUTED },
    StatusLineTerm = { fg = BG, bg = SUCCESS, bold = true }, -- terminal window
    StatusLineTermNC = { fg = BG, bg = SUCCESS }, -- inactive terminal window

    -- ── Floats / borders ──────────────────────────────────────────────────
    NormalFloat = "GreyBg2",
    FloatBorder = { fg = MUTED },
    FloatTitle = { fg = ACCENT, bold = true },

    -- ── Winbar ────────────────────────────────────────────────────────────
    WinBar = { fg = MUTED }, -- breadcrumb bar (focused)
    WinBarNC = { fg = MUTED }, -- breadcrumb bar (unfocused)

    -- ── Window structure ──────────────────────────────────────────────────
    NonText = "GreyFg1",
    EndOfBuffer = "GreyFg1",
    Whitespace = { fg = grey(3) },
    VertSplit = "GreyFg2",
    WinSeparator = "GreyFg2",
    Border = "GreyFg2",

    -- ── Gutter ────────────────────────────────────────────────────────────
    LineNr = "GreyFg3",
    LineNrAbove = "GreyFg2",
    LineNrBelow = "GreyFg2",
    SignColumn = {},
    FoldColumn = "GreyFg2",
    Folded = { fg = MUTED, bg = grey(2) },

    -- ── Diff ──────────────────────────────────────────────────────────────
    DiffAdd = { bg = rgb(0, 1, 0), fg = SUCCESS_BRIGHT },
    DiffDelete = { bg = rgb(1, 0, 0), fg = DANGER_BRIGHT },
    DiffChange = { bg = rgb(1, 1, 0), fg = WARNING },
    DiffText = { bg = rgb(0, 0, 2), bold = true },

    -- ── Treesitter ────────────────────────────────────────────────────────
    ["@variable"] = "Identifier",
    ["@variable.builtin"] = { fg = DANGER },
    ["@variable.parameter"] = { fg = TEXT }, -- plain — params are just vars
    ["@variable.member"] = { fg = ACCENT },

    ["@constant"] = "Constant",
    ["@constant.builtin"] = { fg = WARNING, bold = true },
    ["@constant.macro"] = { fg = WARNING },

    ["@string"] = "String",
    ["@string.escape"] = "SpecialChar",
    ["@string.special"] = "SpecialChar",
    ["@string.regexp"] = { fg = ACCENT_ALT },

    ["@character"] = "Character",
    ["@number"] = "Number",
    ["@float"] = "Float",
    ["@boolean"] = "Boolean",

    ["@function"] = "Function",
    ["@function.builtin"] = { fg = ACCENT_ALT_BRIGHT, bold = true },
    ["@function.macro"] = { fg = ACCENT_ALT },
    ["@function.method"] = { fg = ACCENT_ALT },

    ["@constructor"] = { fg = ACCENT },
    ["@operator"] = "Operator",

    ["@keyword"] = "Keyword",
    ["@keyword.import"] = "Include",
    ["@keyword.return"] = { fg = SUCCESS },
    ["@keyword.exception"] = "Exception",
    ["@keyword.conditional"] = "Conditional",
    ["@keyword.repeat"] = "Repeat",
    ["@keyword.operator"] = { fg = MUTED }, -- subtle — and, or, not recede

    ["@type"] = "Type",
    ["@type.builtin"] = { fg = ACCENT, bold = true },
    ["@type.definition"] = { fg = ACCENT, bold = true },

    ["@module"] = "Identifier", -- module/namespace: plain text
    ["@module.builtin"] = { fg = TEXT, bold = true }, -- built-in modules (io, os, etc.)

    ["@attribute"] = { fg = ACCENT_ALT },
    ["@attribute.builtin"] = { fg = ACCENT_ALT, bold = true },
    ["@property"] = { fg = ACCENT },

    ["@comment"] = "Comment",
    ["@comment.todo"] = "Todo",
    ["@comment.note"] = "Note",
    ["@comment.warning"] = { fg = WARNING, italic = true },
    ["@comment.error"] = { fg = DANGER, italic = true },

    ["@tag"] = { fg = SUCCESS },
    ["@tag.attribute"] = { fg = ACCENT_ALT },
    ["@tag.delimiter"] = { fg = MUTED }, -- <, >, /

    ["@markup.heading"] = { fg = ACCENT, bold = true },
    ["@markup.heading.1"] = { fg = ACCENT, bold = true },
    ["@markup.heading.2"] = { fg = ACCENT, bold = true },
    ["@markup.heading.3"] = { fg = ACCENT, bold = true },
    ["@markup.heading.4"] = { fg = ACCENT, bold = true },
    ["@markup.heading.5"] = { fg = ACCENT, bold = true },
    ["@markup.heading.6"] = { fg = ACCENT, bold = true },
    ["@markup.link"] = { fg = ACCENT, underline = true },
    ["@markup.link.label"] = { fg = ACCENT },
    ["@markup.link.url"] = { fg = ACCENT, underline = true },
    ["@markup.raw"] = { fg = WARNING },
    ["@markup.raw.block"] = { fg = TEXT },
    ["@markup.list"] = { fg = SUCCESS },
    ["@markup.list.checked"] = { fg = ACCENT },
    ["@markup.list.unchecked"] = { fg = MUTED },
    ["@markup.quote"] = "Identifier", -- blockquote body: plain text
    ["@markup.italic"] = { italic = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.link.markdown_inline"] = { fg = MUTED }, -- inline link brackets [ ]
    ["@markup.link.label.markdown_inline"] = { fg = ACCENT }, -- inline link label text
    ["@markup.raw.delimiter.markdown"] = { fg = MUTED }, -- code fence delimiters
    ["@conceal.markdown"] = { fg = MUTED }, -- concealed markdown syntax

    -- ── Diff (treesitter) ─────────────────────────────────────────────────
    ["@diff.plus"] = { fg = SUCCESS_BRIGHT },
    ["@diff.minus"] = { fg = DANGER },
    ["@diff.delta"] = { fg = WARNING },

    -- ── Punctuation ───────────────────────────────────────────────────────
    ["@punctuation.bracket"] = { fg = grey(12) }, -- subtle — ( ) [ ] { } recede
    ["@punctuation.delimiter"] = { fg = grey(10) }, -- subtle — , ; : recede
    ["@punctuation.special"] = { fg = TEXT }, -- subtle — $( ) interpolation

    -- ── String specials ───────────────────────────────────────────────────
    -- @string.special already links to SpecialChar above; add subtypes:
    ["@string.special.symbol"] = { fg = TEXT }, -- text — symbols are identifiers
    ["@string.special.path"] = { fg = ACCENT, underline = true }, -- file paths
    ["@string.special.url"] = { fg = ACCENT, underline = true }, -- URLs

    -- ── Character special ─────────────────────────────────────────────────
    ["@character.special"] = { fg = ACCENT_ALT_BRIGHT, bold = true },

    -- ── Function calls ────────────────────────────────────────────────────
    ["@function.call"] = { fg = ACCENT_ALT },
    ["@function.method.call"] = { fg = ACCENT_ALT },

    -- ── Keyword variants ──────────────────────────────────────────────────
    ["@keyword.function"] = { fg = SUCCESS },
    ["@keyword.storage"] = { fg = ACCENT },
    ["@keyword.debug"] = { fg = ACCENT_ALT },
    ["@keyword.conditional.ternary"] = "Conditional",
    ["@keyword.directive"] = { fg = ACCENT_ALT },
    ["@keyword.directive.define"] = { fg = ACCENT_ALT },

    -- Language-specific overrides
    ["@constructor.lua"] = {},
    ["@variable.member.go"] = { fg = TEXT }, -- go fields plain

    -- ── LSP semantic tokens ───────────────────────────────────────────────
    ["@lsp.type.class"] = "Type",
    ["@lsp.type.enum"] = "Type",
    ["@lsp.type.interface"] = { fg = ACCENT },
    ["@lsp.type.struct"] = "Structure",
    ["@lsp.type.parameter"] = { fg = TEXT },
    ["@lsp.type.variable"] = "Identifier",
    ["@lsp.type.property"] = { fg = ACCENT },
    ["@lsp.type.enumMember"] = "Constant",
    ["@lsp.type.function"] = "Function",
    ["@lsp.type.method"] = { fg = ACCENT_ALT },
    ["@lsp.type.macro"] = { fg = ACCENT_ALT_BRIGHT },
    ["@lsp.type.decorator"] = { fg = ACCENT_ALT_BRIGHT },
    ["@lsp.type.namespace"] = { fg = TEXT },
    ["@lsp.type.comment"] = "Comment",
    ["@lsp.mod.deprecated"] = { fg = MUTED, strikethrough = true },
    ["@lsp.mod.readonly"] = { fg = ACCENT },
    ["@lsp.mod.static"] = { bold = true },

    -- ── LSP UI ────────────────────────────────────────────────────────────
    LspCodeLens = { fg = MUTED }, -- code lens annotation text
    LspCodeLensSeparator = { fg = MUTED }, -- separator between code lens items
    LspInlayHint = { fg = MUTED }, -- inlay hints (type/param names)
    LspReferenceRead = { bg = grey(3) }, -- read-reference under cursor
    LspReferenceText = { bg = grey(3) }, -- text-reference under cursor
    LspReferenceWrite = { bg = grey(4) }, -- write-reference under cursor (slightly brighter)

    -- ── gitsigns ──────────────────────────────────────────────────────────
    GitSignsAdd = { fg = SUCCESS },
    GitSignsChange = { fg = WARNING },
    GitSignsDelete = { fg = DANGER },
    GitSignsChangedelete = { fg = WARNING },
    GitSignsTopdelete = { fg = DANGER },
    GitSignsUntracked = { fg = MUTED },

    GitSignsAddInline = { bg = SUCCESS },
    GitSignsChangeInline = { bg = ACCENT },
    GitSignsDeleteInline = { bg = DANGER },

    -- ── mini.starter ──────────────────────────────────────────────────────
    MiniStarterHeader = { fg = INFO, bold = true },
    MiniStarterFooter = { "Comment" },
    MiniStarterSection = { fg = DANGER },
    MiniStarterItemBullet = { fg = ACCENT },
    MiniStarterItemPrefix = { "WarningMsg", bold = true },
    MiniStarterInactive = { "Comment" },
    MiniStarterQuery = { "WarningMsg", bold = true },

    -- ── mini.tabline ──────────────────────────────────────────────────────
    MiniTablineCurrent = { fg = TEXT, bg = grey(5), bold = true }, -- active tab
    MiniTablineHidden = { fg = MUTED }, -- inactive tab
    MiniTablineModifiedCurrent = { fg = BG, bg = TEXT, bold = true }, -- active modified tab (inverted)
    MiniTablineModifiedHidden = { fg = BG, bg = grey(6) }, -- inactive modified tab
    MiniTablineModifiedVisible = { fg = BG, bg = TEXT }, -- visible modified tab
    MiniTablineVisible = { fg = TEXT }, -- visible non-active tab

    -- ── mini.statusline ───────────────────────────────────────────────────
    MiniStatuslineModeNormal = { bg = ACCENT, fg = BG, bold = true },
    MiniStatuslineModeInsert = { bg = SUCCESS, fg = BG, bold = true },
    MiniStatuslineModeVisual = { bg = ACCENT_ALT, fg = TEXT_BRIGHT, bold = true },
    MiniStatuslineModeReplace = { bg = DANGER, fg = TEXT_BRIGHT, bold = true },
    MiniStatuslineModeCommand = { bg = WARNING, fg = BG, bold = true },
    MiniStatuslineModeOther = { bg = INFO, fg = BG, bold = true },
    MiniStatuslineDevinfo = { bg = grey(4), fg = grey(14) },
    MiniStatuslineFilename = { bg = grey(3), fg = grey(14) },
    MiniStatuslineFileinfo = { bg = grey(2), fg = grey(14) },
    MiniStatuslineInactive = { bg = grey(1), fg = MUTED },
  })
end

return M
